### ISSUE TITLE
Document embed options

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#611]
Types of embeds:

- document
- page
- note
- project

Embeds for reference: https://muckrock.github.io/documentcloud-embed-examples/

**Comment by duckduckgrayduck** [comment]
Documents only (as of the frontend):

Responsive On (default) Off
Width Automatic (default) Fixed
Height Automatic (default) Fixed
Sidebar behavior Responsive (default) Hidden Visible
Title behavior Visible (default) Hidden
PDF link Visible (default) Hidden
Fullscreen option Visible (default) Hidden
Text mode Visible (default) Hidden
Contributed by format User and org (default) Org only 


Documents only (as of WordPress plugin)
height (integer): Height (in pixels) of the embed.
width (integer): Width (in pixels) of the embed. If used, will implicitly set responsive="false".
responsive (boolean): Use responsive layout, which dynamically adjusts width to fill content area. Defaults true.
responsive_offset (integer): Distance (in pixels) to vertically offset the viewer for some responsive embeds.
page (integer): Page number to have the document scroll to by default.
note (integer): ID of the note that the document should highlight by default.
notes (boolean): Hide or show notes.
search (boolean): Hide or show search form.
sidebar (boolean): Hide or show sidebar.
pdf (boolean): Hide or show link to download original PDF.
text (boolean): Hide or show text tab.
zoom (boolean): Hide or show zoom slider.
format (string): Indicate to the theme that this is a wide asset by setting this to wide. Defaults normal.

The note and page embeds seem to call a JS file to generate the embed instead of an oembed resource 
example: 

<div id="DC-note-2578905" class="DC-embed DC-embed-note DC-note-container" style="max-width:750px"></div>
<script src="https://www.documentcloud.org/notes/loader.js;"></script>
<script>
  dc.embed.loadNote('https://embed.documentcloud.org/documents/25030408-dcl20240801/annotations/2578905.js');
</script>
<noscript>
  <a href="https://embed.documentcloud.org/documents/25030408-dcl20240801/annotations/2578905">View note</a>
</noscript>

From what I've tested the only modifiable option for notes is max-width. 

For pages, it appears on the front to have a lot of options for styling
<div class="DC-embed" style="font-family: Source Sans Pro, Avenir Next, Avenir, Helvetica Neue, Helvetica, Arial, sans-serif; max-width: 700px; background: rgb(244, 244, 244); padding: 18px 20px; box-sizing: border-box; border: solid 1px gainsboro; border-radius: 3px;">
  <div style="font-size:14px;line-height:18px;">
    Page 1 of <a class="DC-embed-resource" style="color:#5a76a0;text-decoration:underline;" href="https://embed.documentcloud.org/documents/25030408-dcl20240801/#document/p1" title="View entire dcl20240801 on DocumentCloud in new window or tab" target="_blank"> dcl20240801</a>
  </div>
  <img src="//s3.documentcloud.org/documents/25030408/pages/dcl20240801-p1-xlarge.gif?ts=1722784009" alt="Page 1 of dcl20240801" style="max-width:100%;height:auto;margin:0.5em 0;border:1px solid #ccc;-webkit-box-sizing:border-box;box-sizing:border-box;clear:both" />
  <div style="font-size:14px;line-height:18px;text-align:center">
    Contributed to <a href="https://www.documentcloud.org" title="Go to DocumentCloud in new window or tab" target="_blank" style="color:#5a76a0;text-decoration:underline;font-weight:700;font-family:Gotham,inherit,sans-serif;color:inherit;text-decoration:none">DocumentCloud</a> by Sanjin (MuckRock Staff) &bull; <a style="color: #5a76a0; text-decoration: underline;" href="https://embed.documentcloud.org/documents/25030408-dcl20240801/#document/p1" title="View entire dcl20240801 on DocumentCloud in new window or tab" target="_blank">View document</a> or <a style="color: #5a76a0; text-decoration: underline;" href="s3.documentcloud.org/documents/25030408/pages/dcl20240801-p1.txt?ts=1722784009" title="Read the text of page 1 of dcl20240801 on DocumentCloud in new window or tab" target="_blank">read text</a>
  </div>
</div>
<script src="https://www.documentcloud.org/embed/enhance.js"></script>

but any time I try to make a styling or front change in my iframe tester here:
https://codepen.io/SnapToPixels/pen/BjgvRM
it loads the change for a second and then reverts to the defaults. 



Project embed options have some options I can find:

title - allows you to set a title for the project embed on the page itself (set in the src URL with &title=title_here)
searchbar - (shows the button "Search this document collection") which links you to the project on DocumentCloud. Defaults to 0 (false). 
title - (specified under src) This doesn't do the same thing as title specified above. I'm not sure that it does anything. 
width 
height

**Comment by duckduckgrayduck** [comment]
Added to notion for review at next project planning:
https://www.notion.so/muckrock/DocumentCloud-Embed-Options-3d942017b5794cd2ac53dec204a51bd3
