### ISSUE TITLE
Dismissing an add-on closes the process window

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud-frontend#857]
Dismissing an add-on closes the processing window, which makes dismissing multiple add-on runs tedious.  This is low priority.

**Comment by allanlasser** [comment]
I've narrowed down this issue to [our Dropdown component's `closeOnEventOutside` handler](https://github.com/MuckRock/documentcloud-frontend/blob/a8adb458363dad819e51f530852d53eedc5fb441/src/lib/components/common/Dropdown.svelte#L77-L85). The dropdown is closing because the dismiss button fails a check for `dropdown.contains(event.target)`. I'm not sure why this is happening, as the button is definitely in the `dropdown` node's tree.

**Comment by allanlasser** [comment]
OK, I've narrowed this down further. Because we're performing an optimistic on dismiss, the tree is rerendering before the "clickOutside" handler is triggered. Once the handler is triggered, the target is no longer a child of the tree.
